# Используем базовый образ Nginx
FROM nginx:alpine

# Копируем собранное приложение в директорию, которую обслуживает Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Открываем порт 80 для доступа к приложению
EXPOSE 80

# Запуск Nginx
CMD ["nginx", "-g", "daemon off;"]
