# Используем базовый образ Nginx
FROM nginx:alpine

# Определяем аргумент для версии сборки
ARG BUILD_NUMBER

# Копируем собранное приложение из этапа сборки в директорию, которую обслуживает Nginx
COPY --from=sergiiops/my-react-app:${BUILD_NUMBER} /app/build /usr/share/nginx/html

# Открываем порт 80 для доступа к приложению
EXPOSE 80

# Запуск Nginx
CMD ["nginx", "-g", "daemon off;"]
