# Используем базовый образ Nginx
FROM nginx:alpine

# Копируем собранное приложение из этапа сборки в директорию, которую обслуживает Nginx
COPY --from=my-react-app /app/build /usr/share/nginx/html

# Копируем конфигурационный файл Nginx
# COPY nginx.conf /etc/nginx/nginx.conf

# Открываем порт 80 для доступа к приложению
EXPOSE 80

# Запуск Nginx
CMD ["nginx", "-g", "daemon off;"]

